version: '2'

services:
  app:
    image: node:alpine
    build:
      context: .
    volumes:
      - '.:/app'
    working_dir: '/app'
  install:
    extends:
      service: app
    command: npm install
  test:
    extends:
      service: app
    command: npm run test